### ISSUE TITLE
ComboBox PhET-iO API revision

### ISSUE THREAD

**Issue by arouinfar** [phetsims/sun#922]
Related to https://github.com/phetsims/phet-io/issues/1989

**Other related issues**
@zepumph @samreid I've identified several issues to triage (and possibly address) as part of this work. I did not add these issues to the project board, since I don't know whether or not they will be in scope. I've linked to specific comments where it seems helpful. 
- [x] https://github.com/phetsims/sun/issues/451#issuecomment-2541956281
- [x] https://github.com/phetsims/sun/issues/458
- [x] https://github.com/phetsims/sun/issues/420#issuecomment-478828975 -- ComboBox work seems done, but worth a quick check to verify.
- [x] ~https://github.com/phetsims/sun/issues/462~
- [ ] https://github.com/phetsims/sun/issues/617
- [x] ~https://github.com/phetsims/sun/issues/812~
- [x] https://github.com/phetsims/sun/issues/845
- [x] ~https://github.com/phetsims/sun/issues/849~
- [ ] https://github.com/phetsims/sun/issues/860#issuecomment-2305353473
- [ ] https://github.com/phetsims/sun/issues/921
- [x] ~In case I missed something in the list above, here are all of the [open issues](https://github.com/phetsims/sun/issues?q=is%3Aissue+is%3Aopen+combobox) in sun referencing ComboBox.~

**In general**
- [x] (to be done in https://github.com/phetsims/scenery/issues/1676) Review the listeners and emitters to determine if there are redundancies.
- [x] Determine what migration rules will be necessary.

**Design requests**
- [x] Add assertions to remind devs that there should be a LinkedElement to the associated Property and that the Property itself should be featured. (Overlaps with https://github.com/phetsims/sun/issues/921.)
- [x] Verify that these Properties are `phetioFeatured: true`. And if not, feature them.
   - [x] `comboBox.visibleProperty`
   - [x] `comboBox.enabledProperty`
   - [x] `comboBox.displayOnlyProperty`
   - [x] `comboBox.listBox.*Item.visibleProperty`
- [x] Uninstrument `comboBox.button.enabledProperty`. Disabling a ComboBox via its button will result in a grayscale appearance, which is undesirable. Clients should be using the top-level `enabledProperty` instead. (Migration rule to rename it to the top level enabledProperty).

**Comment by samreid** [comment]
> Review the listeners and emitters to determine if there are redundancies.

ComboBox currently has this structure:

<img width="293" alt="image" src="https://github.com/user-attachments/assets/1b1294fd-5b15-40ca-8ff5-55d4c3959320" />

So I believe we could uninstrument the `pressListener` and just use the `firedEmitter`.  @zepumph has been working on related parts in https://github.com/phetsims/scenery/issues/1676, so I should consult with him about this before proceeding.

**Comment by samreid** [comment]
@arouinfar should the `visibleProperty` move from the button up one level? It seems odd that the `comboBox` doesn't have a `visibleProperty`.

**Comment by samreid** [comment]
> Uninstrument comboBox.button.enabledProperty. Disabling a ComboBox via its button will result in a grayscale appearance, which is undesirable. Clients should be using the top-level enabledProperty instead. (Migration rule to rename it to the top level enabledProperty).

I had proposed the migration processor for this, but now believe moving the enabledProperty state from button up to the combo box will be high cost and low value. Clients probably did not use this at all, and if they did disable combo boxes, they likely did it via the comboBox.enabledProperty. And if we find out otherwise, we can spend the time then.

**Comment by zepumph** [comment]
I think [this](https://github.com/phetsims/sun/commit/861ae01c352e4964c39e781d08c56521228f7941) commit above is breaking the migration wrapper for CAV. Can you take a look at that while I review this issue?

**Comment by samreid** [comment]
Thanks, I pushed a migration processor for CAV. Not sure why I missed it before, perhaps flaky aqua phet-io fuzzing on my part? Not sure.

**Comment by arouinfar** [comment]
> @arouinfar should the visibleProperty be deleted from the comboBox.button?

Excellent suggestion @samreid. Yes, let's uninstrument `comboBox.button.visibleProperty`.

**Comment by zepumph** [comment]
Alright. I believe we are all set. I uninstrumented the button visibleProperty, and updated migration rules (thanks @samreid for making this easy because we already did this with enabledProperty).

Closing
